# Model parameters
name: SOD_v1

model:
  _target_: model.SOD_v1
  input_length: 150
  transition_penalty_weight: 0.2
  smoothness_weight: 0.1
  label_smoothing: 0.05
  num_classes: 3
  learning_rate: 0.01
  nhead: 2
  num_attention_layers: 2
  dim_feedforward: 128
  dropout: 0.1
  lr_decay_factor: 0.75
  lr_decay_nstep: 5

  pred_threshold: 0.8
  resblock_config:
    - in_filters: 1
      out_filters: 16
      dilation: 1
      is_resid: False
    - in_filters: 16
      out_filters: 16
      dilation: 2
    - in_filters: 16
      out_filters: 32
      dilation: 3
    - in_filters: 32
      out_filters: 32
      dilation: 4
    - in_filters: 32
      out_filters: 32
      dilation: 5
    - in_filters: 32
      out_filters: 32
      dilation: 6

datamodule:
  _target_: dataset.WindowedEEGDataModule
  window_length: 150
  batch_size: 256
  num_workers: 6
  train_dir: "data/processed/train"
  val_dir: "data/processed/val"
  test_dir: "data/processed/test"
  stride: 50
  keep_ratio: 1.5
  apply_savgol: 0
  deriv: 0
  transforms:
      - _target_: utils.transforms.population_zscore_transform

# Trainer configuration
trainer:
  max_epochs: 100
  #precision: 16
  log_every_n_steps: 1
