_target_: model.BaseModel
encoder:
  _target_: networks.TransformerEncoderModel
  resblock_config:
    - in_filters: 1
      out_filters: 16
      dilation: 1
      is_resid: true
    - in_filters: 16
      out_filters: 16
      dilation: 2
    - in_filters: 16
      out_filters: 32
      dilation: 4
    - in_filters: 32
      out_filters: 32
      dilation: 8
    - in_filters: 32
      out_filters: 32
      dilation: 16
  nhead: 8
  num_attention_layers: 4
  dim_feedforward: 128
  dropout: 0.1
  return_valid: true
decoder:
  _target_: networks.LinearDecoder
  input_dim: 128
  intermediate_dim: 128
  num_classes: 3
loss_fn:
  _target_: losses.CEtransitionLoss
  smoothness_weight: 0.2
  transition_penalty_weight: 0.2
  label_smoothing: 0.05
learning_rate: 0.001
weight_decay: 1.0e-06
return_valid: false
lr_scheduler_config:
  step_size: 10
  gamma: 0.5
