defaults:
  - model: base
  - datamodule: base
  - trainer: base
  - loss: base
  - override hydra/launcher: cluster_slurm
  - _self_

hydra:
  run:
    dir: ${log_dir}/runs/${hydra.job.override_dirname}  # Save Hydra run-specific outputs in log_dir
  sweep:
    dir: ${log_dir}/sweeps/${name}_${now:%Y-%m-%d_%H-%M-%S}

name: SOD_trans-lin_comp-attention_lay_long

log_dir: /cs/home/naehert/projects/SODeep/logs/${now:%Y-%m-%d_%H-%M-%S}  # Central directory
