# General settings
experiment_name: "Experiment 001"
save_dir: "experiments/experiment_001/"

# Data settings
data:
  train_file: "data/processed/train.h5"
  val_file: "data/processed/val.h5"
  test_file: "data/processed/test.h5"
  batch_size: 64
  shuffle: true

# Model settings
model:
  input_size: 1000
  hidden_size: 128
  num_layers: 2
  dropout: 0.5

# Training settings
training:
  num_epochs: 50
  learning_rate: 0.001
  optimizer: "adam"
  loss: "cross_entropy"

# Logging
logging:
  log_interval: 10