_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

submitit_folder: ./.submitit/${now:%Y-%m-%d_%H-%M-%S}
partition: GPUlong
job_name: "hydra_sweep"
additional_parameters:
  gres: "gpu:rtxa6000:1"

time: "2-00:00:00"

setup:
  - module load conda
  - conda activate sodeep
