_target_: dataset.WindowedEEGDataModule
window_length: 150
batch_size: 256
num_workers: 6
train_dir: data/processed/train
val_dir: data/processed/val
test_dir: data/processed/test
stride: 50
keep_ratio: 1.5
apply_savgol: 0
deriv: 0
transforms:
  - _target_: utils.transforms.population_zscore_transform